### ISSUE TITLE
Copyrighting Request

### ISSUE THREAD

**Issue by tony-duke** [RagePeanut/Tweem#1]
Hello, I am Tony, i went through your project and i want to say it is very nice bot. However i noticed you are missing out some important details like faq, about us and privacy policy which users will be looking forward too. If you dont mind i can write that for you and also help in any other possible way so as to aid your project

contact me
email anthonynduka0@gmail.com

**Comment by RagePeanut** [comment]
I appreciate you wanting to help but these are not necessary, and if they happen to be one day I'll take care of them. Thanks though !
