### ISSUE TITLE
LOGO PROPOSAL for TWEEM

### ISSUE THREAD

**Issue by chrisjasonoswa** [RagePeanut/Tweem#2]
I have observed that Tweem has no official logo yet so here is my logo proposal for tweem. I am open to any suggestions and changes to improve this logo :)
![twecover](https://user-images.githubusercontent.com/38552359/40042093-b467090a-5852-11e8-8c5b-acf168e6df7b.png)

![tweicon](https://user-images.githubusercontent.com/38552359/40041960-58f3be42-5852-11e8-8a4d-b5496227339b.png)
<h1>Logo Icon</h1>

![tweiconvariations](https://user-images.githubusercontent.com/38552359/40041961-5943231a-5852-11e8-845c-92a1c3139200.png)

<h1>Logo Type</h1>

![twelogotype](https://user-images.githubusercontent.com/38552359/40041962-5994311a-5852-11e8-90b9-6ea19951f460.png)

![twelogotypevaritaions](https://user-images.githubusercontent.com/38552359/40041963-5a59d4c4-5852-11e8-8d35-9ba80be70913.png)

![twemonochrome](https://user-images.githubusercontent.com/38552359/40042472-1e080ca0-5854-11e8-8f7a-eaa694418c1a.png)

![twemonochrome1](https://user-images.githubusercontent.com/38552359/40042832-42be53aa-5855-11e8-9422-afb566449425.png)

**Comment by RagePeanut** [comment]
Hey, sorry, just saw it today. Thanks for you proposal but I'll have to pass. It looks good but doesn't represent what Tweem is about (automated post sharing on multiple platforms).
